services: 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: personal_project
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moneyDB
    ports:
      - "5432:5432"
    networks:
      - backend
    heatlcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moneyDB"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:
